
const defaultTracks = [
  {title:'Money',artist:'Blocboykiddie',type:'Single',link:'https://songwhip.com/blocboykiddie'},
  {title:'Wacko Jacko',artist:'Blocboykiddie',type:'Single',link:'https://songwhip.com/blocboykiddie'},
  {title:'Lean Gone Cold',artist:'Blocboykiddie',type:'Single',link:'https://songwhip.com/blocboykiddie'}
];
const defaultArtists = [{name:'Blocboykiddie', genre:'Hip-Hop / Afro-fusion / Melodic Trap', status:'Active'}, {name:'Future Artist Slot 02', genre:'Open', status:'Pipeline'}, {name:'Future Artist Slot 03', genre:'Open', status:'Pipeline'}];
function getStore(key,fallback){try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))}catch(e){return fallback}}
function setStore(key,value){localStorage.setItem(key,JSON.stringify(value))}
function tracksStore(){return getStore('nebulaDashboardTracks',defaultTracks)} function artistsStore(){return getStore('nebulaDashboardArtists',defaultArtists)} function eventsStore(){return getStore('nebulaAnalyticsEvents',[])}
function switchTab(tab){document.querySelectorAll('.dash-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));document.querySelectorAll('.dash-panel').forEach(p=>p.classList.toggle('active',p.dataset.panel===tab));drawCharts()}
function renderStats(){const tracks=tracksStore(), events=eventsStore(), leads=getStore('nebulaDemoLeads',[]);document.getElementById('dashPlays').textContent=events.length;document.getElementById('dashUploads').textContent=tracks.length;document.getElementById('dashLeads').textContent=leads.length}
function renderTracks(){const table=document.getElementById('trackTable'); if(!table)return; table.innerHTML=tracksStore().map(t=>`<tr><td>${t.title}</td><td>${t.artist}</td><td>${t.type||'Single'}</td><td><a href="${t.link||'#'}" target="_blank" rel="noopener">Open ↗</a></td></tr>`).join('')}
function renderArtists(){const wrap=document.getElementById('artistPipeline'); if(!wrap)return; wrap.innerHTML=artistsStore().map((a,i)=>`<article class="pipeline-card"><span>${a.status||'Pipeline'}</span><h3>${a.name}</h3><p>${a.genre||'Open genre'}</p>${i>0?`<button data-remove-artist="${i}" class="mini-play" type="button">Remove</button>`:''}</article>`).join(''); wrap.querySelectorAll('[data-remove-artist]').forEach(btn=>btn.addEventListener('click',()=>{const arr=artistsStore();arr.splice(Number(btn.dataset.removeArtist),1);setStore('nebulaDashboardArtists',arr);renderArtists()}))}
function addTrack(e){e.preventDefault();const data=Object.fromEntries(new FormData(e.target).entries());const file=e.target.audio.files[0];const arr=tracksStore();arr.unshift({title:data.title,artist:data.artist,type:data.type,link:data.link,file:file?file.name:'metadata-only'});setStore('nebulaDashboardTracks',arr);e.target.reset();renderTracks();renderStats();switchTab('uploads')}
function addArtist(e){e.preventDefault();const data=Object.fromEntries(new FormData(e.target).entries());const arr=artistsStore();arr.push({name:data.name,genre:data.genre||'Open',status:'Pipeline'});setStore('nebulaDashboardArtists',arr);e.target.reset();renderArtists();renderStats()}
function drawChart(id, values){const canvas=document.getElementById(id); if(!canvas)return; const ctx=canvas.getContext('2d'), w=canvas.width=canvas.offsetWidth*devicePixelRatio, h=canvas.height=Number(canvas.getAttribute('height'))*devicePixelRatio; ctx.clearRect(0,0,w,h); ctx.scale(devicePixelRatio,devicePixelRatio); const cw=canvas.offsetWidth,ch=Number(canvas.getAttribute('height')); ctx.strokeStyle='rgba(7,17,38,.10)'; ctx.lineWidth=1; for(let i=0;i<5;i++){ctx.beginPath();ctx.moveTo(0,(ch/5)*i);ctx.lineTo(cw,(ch/5)*i);ctx.stroke()} const max=Math.max(...values,1); ctx.beginPath(); values.forEach((v,i)=>{const x=(cw/(values.length-1))*i;const y=ch-(v/max)*(ch-18)-8; if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)}); const grad=ctx.createLinearGradient(0,0,cw,0); grad.addColorStop(0,'#62d66b'); grad.addColorStop(.5,'#60e7ff'); grad.addColorStop(1,'#3a77ff'); ctx.strokeStyle=grad; ctx.lineWidth=4; ctx.lineCap='round'; ctx.stroke(); }
function drawCharts(){const events=eventsStore();const dayCounts={};for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);dayCounts[d.toISOString().slice(0,10)]=0}events.forEach(e=>{const k=(e.date||'').slice(0,10);if(k in dayCounts)dayCounts[k]++});const vals=Object.values(dayCounts);drawChart('overviewChart',vals);drawChart('analyticsChart',vals)}
function simulateEvent(){const events=eventsStore();events.push({type:'play',track:'Money',artist:'Blocboykiddie',date:new Date().toISOString()});setStore('nebulaAnalyticsEvents',events);renderStats();drawCharts()}
function exportReport(){const payload={generated:new Date().toISOString(),tracks:tracksStore(),artists:artistsStore(),events:eventsStore(),leads:getStore('nebulaDemoLeads',[])};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='nebula-records-dashboard-report.json';a.click();URL.revokeObjectURL(a.href)}
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('.dash-tabs button').forEach(btn=>btn.addEventListener('click',()=>switchTab(btn.dataset.tab)));document.querySelectorAll('[data-jump]').forEach(btn=>btn.addEventListener('click',()=>switchTab(btn.dataset.jump)));document.getElementById('uploadForm')?.addEventListener('submit',addTrack);document.getElementById('artistForm')?.addEventListener('submit',addArtist);document.getElementById('simulateEvent')?.addEventListener('click',simulateEvent);document.getElementById('resetAnalytics')?.addEventListener('click',()=>{localStorage.setItem('nebulaAnalyticsEvents','[]');renderStats();drawCharts()});document.getElementById('exportDashboard')?.addEventListener('click',exportReport);renderTracks();renderArtists();renderStats();drawCharts()});
